.TH lgcadm 1 "November 2022" "User Manuals"
.SH NAME
lgcadm \- Manage little green clusters
.SH SYNOPSIS
.B lgcadm
[command] [options...]
.SH COMMANDS
.IP get-log
Fetches logs from lgcsrv
.IP put-log
Puts message into log buffer
.IP get-var
Fetches key/value pair from server
.IP put-var
Puts key/value pair into servers environment
.IP get-route
Fetches the proxy route list from the server
.IP put-route
Puts a new route in place
